// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./src/components/A/index.vue')['default']
    B: typeof import('./src/components/B/index.vue')['default']
    C: typeof import('./src/components/C/index.vue')['default']
    Card: typeof import('./src/components/Card/index.vue')['default']
    Dialog: typeof import('./src/components/Dialog/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/expame/skeleton.vue')['default']
    Sync: typeof import('./src/components/expame/sync.vue')['default']
    Tree: typeof import('./src/components/Tree/index.vue')['default']
    WaterFall: typeof import('./src/components/water-fall/water-fall.vue')['default']
  }
}
