// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./src/components/A/index.vue')['default']
    Card: typeof import('./src/components/Card/index.vue')['default']
    Dialog: typeof import('./src/components/Dialog/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Tree: typeof import('./src/components/Tree/index.vue')['default']
  }
}
